### ISSUE TITLE
advertising_spots KeyError output

### ISSUE THREAD

**Issue by opalmer-lopez** [coppeliaMLA/pybarb#15]
Hi! 

I keep encountering an error when I try to execute a query using the "advertising_spots" function within the pybarb library. When I try to use this I get a KeyError message that "spot_start_datetime" is not a key.

Attached is the image containing the code I have tried to run alongside the error message for reference. 
Please let me know if you require any further information. 

<img width="1058" alt="image" src="https://github.com/coppeliaMLA/pybarb/assets/109656403/81640520-456c-4143-989c-73ea042e3890">

Many thanks,
Omar

**Comment by coppeliaMLA** [comment]
Hi @opalmer-lopez. No problem. This is just because spot_start_datetime, although it is a field in the returned data, is not one of the query parameters for the API. See [here](https://barb-api.co.uk/api-docs#tag/Events/operation/listAdvertisingSpots) for a list of the available parameters for this endpoint. If you are after a particular spot event then you could use the available query parameters to narrow down the dataset and then filter the results at your end.

**Comment by coppeliaMLA** [comment]
Hi @opalmer-lopez - it's definitely working for me. Could you post your exact code? 

Also does the example in the Getting Started notebook work for you? That is

```
itv_1_spots = barb_api.advertising_spots("2020-01-01", "2020-01-02", 
                           station="ITV1", panel="bbc network", 
                           buyer="mediacom_dublin",
                           consolidated=True, limit=5000)
itv_1_spots.to_dataframe()
```

**Comment by coppeliaMLA** [comment]
Ah got it - I've managed to replicate it. Looking at it now

**Comment by coppeliaMLA** [comment]
No problem. On the other issue you can now do this - see #14

**Comment by coppeliaMLA** [comment]
Hi @opalmer-lopez just checking that everything is working ok for you now

**Comment by coppeliaMLA** [comment]
No problem. Can I add you as collaborator to the repo? You could then make fixes to issues when you find them.

**Comment by coppeliaMLA** [comment]
Tantastic
